/**
 * FUND.lab — API Layer: catalog.js
 * Catalogue des modules diagnostics disponibles
 */

export const MODULES_CATALOG = {
  'PRJ-02': {
    id: 'PRJ-02',
    name: 'Diagnostic Projet',
    shortName: 'Projet',
    description: 'Évaluez la maturité de votre idée ou projet avant le lancement.',
    icon: 'Rocket',
    duration: '8-12 min',
    questions: 8,
    axes: ['Concept & problème', 'Clientèle cible', 'Modèle économique', 'Financement', 'Concurrence', 'Compétences'],
    outputLabel: 'Maturité du projet',
    recommendedFor: ['project'],
    color: '#2659F2',
  },
  'FLH-01': {
    id: 'FLH-01',
    name: 'Diagnostic Flash',
    shortName: 'Flash',
    description: 'Un check-up rapide pour comprendre globalement l\'état de votre activité.',
    icon: 'Zap',
    duration: '7-10 min',
    questions: 7,
    axes: ['Ventes', 'Trésorerie', 'Clients', 'Marché', 'Stratégie', 'Difficultés'],
    outputLabel: 'Santé globale',
    recommendedFor: ['active'],
    color: '#00b8a3',
  },
  'DIF-03': {
    id: 'DIF-03',
    name: 'Diagnostic Difficulté',
    shortName: 'Difficulté',
    description: 'Analysez et hiérarchisez les tensions de votre entreprise pour trouver des solutions.',
    icon: 'AlertTriangle',
    duration: '10-15 min',
    questions: 10,
    axes: ['Nature de la difficulté', 'Durée', 'Dettes', 'Trésorerie', 'Accompagnement', 'Moral'],
    outputLabel: 'Niveau d\'urgence',
    recommendedFor: ['diffic', 'active'],
    color: '#ef4444',
    urgent: true,
  },
  'OPP-04': {
    id: 'OPP-04',
    name: 'Diagnostic Opportunité',
    shortName: 'Opportunité',
    description: 'Évaluez si votre entreprise est prête à saisir une opportunité identifiée.',
    icon: 'Target',
    duration: '10-15 min',
    questions: 6,
    axes: ['Nature de l\'opportunité', 'Délai', 'Trésorerie', 'Ressources humaines', 'Risques', 'Alignement stratégique'],
    outputLabel: 'Niveau de préparation',
    recommendedFor: ['opport', 'active', 'pme'],
    color: '#f59e0b',
    disclaimer: 'Ce diagnostic ne constitue pas une validation d\'éligibilité à un financement.',
  },
  'PRO-05': {
    id: 'PRO-05',
    name: 'Diagnostic Offre & Produits',
    shortName: 'Offre & Prix',
    description: 'Clarifiez et optimisez votre offre, vos produits et votre positionnement prix.',
    icon: 'Lightbulb',
    duration: '8-15 min',
    questions: 6,
    axes: ['Clarté de l\'offre', 'Ciblage client', 'Marges', 'Retours clients', 'Positionnement prix', 'Innovation'],
    outputLabel: 'Clarté de l\'offre',
    recommendedFor: ['active', 'pme'],
    color: '#8b5cf6',
  },
  'COM-06': {
    id: 'COM-06',
    name: 'Diagnostic Commercial',
    shortName: 'Commercial',
    description: 'Analysez votre processus de vente, acquisition clients et fidélisation.',
    icon: 'Users',
    duration: '8-15 min',
    questions: 7,
    axes: ['Processus de vente', 'Indicateurs', 'Acquisition', 'Rétention', 'Fidélisation', 'Marketing'],
    outputLabel: 'Performance commerciale',
    recommendedFor: ['active', 'pme'],
    color: '#3b82f6',
  },
  'FIN-07': {
    id: 'FIN-07',
    name: 'Diagnostic Financier',
    shortName: 'Finance',
    description: 'Évaluez la santé financière de votre activité : trésorerie, rentabilité, dettes.',
    icon: 'TrendingUp',
    duration: '8-15 min',
    questions: 8,
    axes: ['Suivi trésorerie', 'Point mort', 'Rentabilité', 'Dettes', 'Créances', 'Prévisionnel', 'Financement'],
    outputLabel: 'Santé financière',
    recommendedFor: ['active', 'pme', 'diffic'],
    color: '#10b981',
  },
  'GOV-08': {
    id: 'GOV-08',
    name: 'Diagnostic Organisation',
    shortName: 'Organisation',
    description: 'Évaluez la gouvernance, les rôles et les processus de décision de votre entreprise.',
    icon: 'Building2',
    duration: '8-15 min',
    questions: 6,
    axes: ['Rôles & responsabilités', 'Décisions', 'Réunions', 'Stratégie partagée', 'Indicateurs', 'Équipe'],
    outputLabel: 'Maturité organisationnelle',
    recommendedFor: ['pme'],
    color: '#0A1745',
  },
  '360-09': {
    id: '360-09',
    name: 'Diagnostic 360°',
    shortName: '360° Complet',
    description: 'Un bilan complet de toutes les dimensions de votre entreprise.',
    icon: 'Award',
    duration: '30-45 min',
    questions: 10,
    axes: ['Offre', 'Commercial', 'Finance', 'Organisation', 'Opérations', 'Équipe', 'Digital', 'Défis'],
    outputLabel: 'Score global 360°',
    recommendedFor: ['pme'],
    color: '#0A1745',
    premium: true,
  },
};

export const MODULES_LIST = Object.values(MODULES_CATALOG);

export const getModule = (id) => MODULES_CATALOG[id] || null;

export const MODULE_ROUTES = {
  'S10': 'PRJ-02',
  'S11': 'DIF-03',
  'S12': 'OPP-04',
  'S13': 'FLH-01',
};

// Legacy compat — map old format to new
export const MODULE_BY_ROUTE = {
  'S10': { id: 'PRJ-02', name: 'Diagnostic Projet', duration: '8-12 min' },
  'S11': { id: 'DIF-03', name: 'Diagnostic Difficulté', duration: '10-15 min' },
  'S12': { id: 'OPP-04', name: 'Diagnostic Opportunité', duration: '10-15 min' },
  'S13': { id: 'FLH-01', name: 'Diagnostic Flash', duration: '7-10 min' },
};
