/**
 * FUND.lab — API Layer: profiles.js
 * Définition des 6 profils utilisateur avec leurs routes et thèmes visuels
 */

export const PROFILES = {
  project: {
    id: 'project',
    label: 'Porteur de Projet',
    sublabel: "J'ai une idée ou un projet, pas encore lancé",
    description: 'Vous avez une idée ou un projet en cours de préparation. Validez la maturité de votre concept.',
    icon: 'Rocket',
    color: '#2659F2',
    colorLight: 'rgba(38, 89, 242, 0.08)',
    colorBorder: 'rgba(38, 89, 242, 0.25)',
    journey: ['Profil', 'Contexte', 'Signaux', 'Diagnostic Projet', 'Résultats'],
    defaultModule: 'PRJ-02',
    tag: 'Porteur',
    tagColor: '#2659F2',
  },
  active: {
    id: 'active',
    label: 'Entrepreneur Actif',
    sublabel: "J'ai déjà une activité qui vend",
    description: 'Vous vendez déjà des produits ou services et souhaitez analyser, améliorer ou développer votre activité.',
    icon: 'Store',
    color: '#00b8a3',
    colorLight: 'rgba(0, 184, 163, 0.08)',
    colorBorder: 'rgba(0, 184, 163, 0.25)',
    journey: ['Profil', 'Contexte', 'Signaux', 'Diagnostic Flash', 'Résultats'],
    defaultModule: 'FLH-01',
    tag: 'Actif',
    tagColor: '#00b8a3',
  },
  pme: {
    id: 'pme',
    label: 'PME / TPE Structurée',
    sublabel: "Je dirige une PME déjà structurée",
    description: 'Votre entreprise dispose d\'une équipe et de processus établis. Faites un bilan 360° ou ciblez un axe.',
    icon: 'Building2',
    color: '#0A1745',
    colorLight: 'rgba(10, 23, 69, 0.06)',
    colorBorder: 'rgba(10, 23, 69, 0.20)',
    journey: ['Profil', 'Contexte', 'Signaux', 'Diagnostic 360°', 'Résultats'],
    defaultModule: '360-09',
    tag: 'PME',
    tagColor: '#0A1745',
  },
  diffic: {
    id: 'diffic',
    label: 'En Difficulté',
    sublabel: "Mon entreprise traverse une difficulté",
    description: 'Votre activité face à des tensions financières, commerciales ou opérationnelles. Agissez rapidement.',
    icon: 'AlertTriangle',
    color: '#ef4444',
    colorLight: 'rgba(239, 68, 68, 0.08)',
    colorBorder: 'rgba(239, 68, 68, 0.25)',
    journey: ['Profil', 'Signaux critiques', 'Diagnostic Difficulté', 'Plan d\'action', 'Résultats'],
    defaultModule: 'DIF-03',
    tag: 'Prioritaire',
    tagColor: '#ef4444',
    urgent: true,
  },
  opport: {
    id: 'opport',
    label: 'En Recherche d\'Opportunité',
    sublabel: "Je cherche à saisir une opportunité",
    description: 'Vous avez identifié une opportunité et souhaitez vérifier si votre entreprise est prête à la saisir.',
    icon: 'Target',
    color: '#f59e0b',
    colorLight: 'rgba(245, 158, 11, 0.08)',
    colorBorder: 'rgba(245, 158, 11, 0.25)',
    journey: ['Profil', 'Contexte', 'Vérification risques', 'Diagnostic Opportunité', 'Résultats'],
    defaultModule: 'OPP-04',
    tag: 'Opportunité',
    tagColor: '#f59e0b',
  },
  curious: {
    id: 'curious',
    label: 'Institutionnel / Curieux',
    sublabel: "Je suis simplement curieux / non entrepreneur",
    description: 'Vous êtes partenaire, chercheur, étudiant ou simplement curieux. Découvrez Business Check-up.',
    icon: 'Lightbulb',
    color: '#64748b',
    colorLight: 'rgba(100, 116, 139, 0.08)',
    colorBorder: 'rgba(100, 116, 139, 0.25)',
    journey: ['Page d\'information', 'Contact'],
    defaultModule: null,
    tag: 'Info',
    tagColor: '#64748b',
    redirectTo: '/a-propos',
  },
};

export const PROFILES_LIST = Object.values(PROFILES);

export const getProfile = (id) => PROFILES[id] || null;
